#!/usr/bin/env php
<?php

namespace WebdevToolbox;

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application();
$app->addCommands([
    new Command\Adminer(),
    new Command\DockerShell(),
    new Command\HttpPing(),
]);
$app->run();
