#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use WebdevToolbox\Command\AdminerCommand;

$application = new Application();
$application->add(new AdminerCommand());
$application->run();
